"use strict";
exports.__esModule = true;
var deneme_1 = require("./deneme");
exports.deneme = deneme_1.deneme;
var ders_1 = require("./ders");
exports.Ders = ders_1.Ders;
var devamsizlik_1 = require("./devamsizlik");
exports.Devamsizlik = devamsizlik_1.Devamsizlik;
var hoca_1 = require("./hoca");
exports.Hoca = hoca_1.Hoca;
var ogrenci_1 = require("./ogrenci");
exports.Ogrenci = ogrenci_1.Ogrenci;
var tweet_1 = require("./tweet");
exports.Tweet = tweet_1.Tweet;
